######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 15 11:07:03 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += gotocall.cpp
