######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 13 16:19:30 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    find.cpp

HEADERS += \
    find.h
