######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 23 14:37:17 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    poninter.cpp \
    hasptr.cpp

HEADERS += \
    poninter.h \
    hasptr.h
