######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 20 10:42:42 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Product.h \
    factory.h

SOURCES += \
    Product.cpp \
    factory.cpp \
    maincpp.cpp
