######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 15 15:37:14 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += gotocelldialog.ui
SOURCES += main.cpp
