######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 24 11:07:19 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    handle.cpp

HEADERS += \
    handle.h
