######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 23 16:56:13 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    salesitem.cpp \
    salsebase.cpp

HEADERS += \
    salesitem.h \
    salsebase.h
