######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 13 13:29:30 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
